# Generated by Django 2.2.7 on 2021-10-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20191130_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Название ягоды')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена ягоды')),
            ],
            options={
                'verbose_name': 'Ягода',
                'verbose_name_plural': 'Ягоды',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
                ('phone_number', models.CharField(blank=True, default='', max_length=256, verbose_name='Номер телефона заказчика')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия заказчика')),
                ('address', models.TextField(verbose_name='Адрес заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Decors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Наименование декора')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена декора')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декор',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Наимнование формы')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена формы')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Наимнование уровня')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена уровня')),
            ],
            options={
                'verbose_name': 'Количество уровней',
                'verbose_name_plural': 'Количество уровней',
            },
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=256, verbose_name='Номер телефона заказчика')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Наимнование топпинга')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена топпинга')),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинг',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Надпись')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость заказа')),
                ('berries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.Berries', verbose_name='Ягоды')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Customers', verbose_name='Заказчик')),
                ('decor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.Decors', verbose_name='Декор')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.Forms', verbose_name='Форма')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.Levels', verbose_name='Количество уровней')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.OrderStatuses', verbose_name='Статус заказа')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.Topping', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
