# Generated by Django 2.2.7 on 2021-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_berries_customers_decors_forms_levels_orders_orderstatuses_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.TextField(verbose_name='Дата доставки'),
        ),
    ]
