# Generated by Django 2.2.7 on 2021-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20211031_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.TextField(verbose_name='Время доставки'),
        ),
    ]
