# Generated by Django 2.2.7 on 2021-11-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20211101_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
